#!/usr/bin/env bash
# ============================================================================
# setup_server.sh — one-shot, self-contained server bootstrap.
#
# Creates an isolated Python venv and installs all deps INSIDE the project
# folder. The model cache (HF_HOME) also lives inside the project, so the entire
# footprint is one directory. To remove everything later: `rm -rf <project dir>`
# (or run scripts/uninstall.sh).
#
# Idempotent: safe to re-run. Logs to state/install.log and records a manifest.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT="$(cd "$SCRIPT_DIR/.." && pwd)"
VENV="$PROJECT/.venv"
HF_CACHE="$PROJECT/.hf_cache"
PIP_CACHE="$PROJECT/.pip_cache"
STATE="$PROJECT/state"
REQ="$PROJECT/config/requirements-train.txt"

# Keep ALL caches inside the project so `rm -rf <project>` truly removes
# everything (no stray ~/.cache/pip or ~/.cache/huggingface).
export PIP_CACHE_DIR="$PIP_CACHE"
export HF_HOME="$HF_CACHE"
export HF_HUB_CACHE="$HF_CACHE/hub"
export TRANSFORMERS_CACHE="$HF_CACHE"

mkdir -p "$STATE" "$HF_CACHE" "$PIP_CACHE"
LOG="$STATE/install.log"

# Mirror all output to the install log; wait on the tee child at exit so the
# final lines (incl. any ERROR before exit) are flushed to the log.
exec > >(tee -a "$LOG"); TEE_PID=$!; exec 2>&1
trap 'exec 1>&- 2>&-; wait "$TEE_PID" 2>/dev/null || true' EXIT
echo "============================================================"
echo "setup_server.sh  @ $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo "  PROJECT = $PROJECT"
echo "  VENV    = $VENV"
echo "  HF_HOME = $HF_CACHE"
echo "============================================================"

# --- Python ---
PY="${PYTHON:-python3}"
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "ERROR: python3 not found. Install Python 3.10+ first." >&2
  exit 1
fi
echo "==> Using $("$PY" --version 2>&1) at $(command -v "$PY")"

# --- GPU (warn only) ---
if command -v nvidia-smi >/dev/null 2>&1; then
  echo "==> GPU detected:"
  nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader || true
else
  echo "==> WARNING: nvidia-smi not found. Training needs a CUDA GPU; eval/CPU-only will be slow or fail."
fi

# --- venv ---
if [ ! -d "$VENV" ]; then
  echo "==> Creating venv at $VENV"
  "$PY" -m venv "$VENV"
else
  echo "==> Reusing existing venv at $VENV"
fi
# venv activate scripts can reference unbound vars; relax -u only around sourcing.
set +u
# shellcheck disable=SC1091
source "$VENV/bin/activate"
set -u

echo "==> Upgrading pip/wheel"
python -m pip install -U pip wheel setuptools

if [ ! -f "$REQ" ]; then
  echo "ERROR: requirements file missing: $REQ" >&2
  exit 1
fi
echo "==> Installing core requirements from $REQ"
python -m pip install -r "$REQ"

if python -c "import unsloth" >/dev/null 2>&1; then
  echo "==> Unsloth already present — not reinstalling (avoids churning pinned deps)."
else
  echo "==> Attempting Unsloth (optional fast path; failure is non-fatal)"
  if python -m pip install -U unsloth; then
    echo "    Unsloth installed."
  else
    echo "    Unsloth not installed — the HF + bitsandbytes fallback will be used."
  fi
fi

# Write env.sh + MANIFEST BEFORE the diagnostic snapshot, so a pip-freeze hiccup
# can never leave the run scripts without an env file.
cat > "$PROJECT/env.sh" <<EOF
# Auto-generated by setup_server.sh — source this before running.
export NEOPERI_PROJECT="$PROJECT"
export VIRTUAL_ENV_DIR="$VENV"
export HF_HOME="$HF_CACHE"
export HF_HUB_CACHE="$HF_CACHE/hub"
export TRANSFORMERS_CACHE="$HF_CACHE"
export PIP_CACHE_DIR="$PIP_CACHE"
export HF_HUB_ENABLE_HF_TRANSFER=0
export TOKENIZERS_PARALLELISM=false
EOF

echo "==> Recording environment snapshot"
python -m pip freeze > "$STATE/pip-freeze.txt" || true
python - <<'PY' > "$STATE/torch-check.txt" 2>&1 || true
import torch
print("torch", torch.__version__, "cuda", torch.version.cuda, "is_available", torch.cuda.is_available())
if torch.cuda.is_available():
    print("device", torch.cuda.get_device_name(0))
PY
cat "$STATE/torch-check.txt"

# --- manifest of everything this script created (for easy teardown) ---
cat > "$STATE/MANIFEST.txt" <<EOF
# Footprint created by setup_server.sh — all inside $PROJECT
$VENV/                  python venv (all pip packages)
$HF_CACHE/              Hugging Face model cache (Kumru-2B downloads here)
$PIP_CACHE/             pip wheel/download cache (kept in-project on purpose)
$STATE/                 install log, pip freeze, torch check, this manifest
$PROJECT/env.sh         environment file
$PROJECT/models/        trained LoRA adapters (created during training)
# To delete EVERYTHING:  rm -rf "$PROJECT"
# Or run:                bash "$PROJECT/scripts/uninstall.sh"
EOF

echo ""
echo "==> DONE. Footprint recorded in $STATE/MANIFEST.txt"
echo ""
echo "Next steps (from $PROJECT):"
echo "  1) Put clinician-reviewed data at  data/processed/task_sft.jsonl"
echo "  2) Smoke test:   bash scripts/run_train.sh data/processed/task_sft.jsonl --smoke-only"
echo "  3) Full train:   bash scripts/run_train.sh data/processed/task_sft.jsonl run-01"
echo "  4) Gate/eval:    bash scripts/run_eval.sh --adapter models/kumru-neoperi-lora-run-01 \\"
echo "                       --redteam data/redteam/redteam.example.jsonl"
echo "  Teardown:        bash scripts/uninstall.sh   (or rm -rf \"$PROJECT\")"
